export * from './authAPI.service';
import { AuthAPIService } from './authAPI.service';
export * from './branchAPI.service';
import { BranchAPIService } from './branchAPI.service';
export * from './branchScheduleAPI.service';
import { BranchScheduleAPIService } from './branchScheduleAPI.service';
export * from './employeeAPI.service';
import { EmployeeAPIService } from './employeeAPI.service';
export * from './mailPackageAPI.service';
import { MailPackageAPIService } from './mailPackageAPI.service';
export * from './mailPackageAssignationAPI.service';
import { MailPackageAssignationAPIService } from './mailPackageAssignationAPI.service';
export * from './mailPackageStatusAPI.service';
import { MailPackageStatusAPIService } from './mailPackageStatusAPI.service';
export * from './permissionAPI.service';
import { PermissionAPIService } from './permissionAPI.service';
export * from './servicePriceAPI.service';
import { ServicePriceAPIService } from './servicePriceAPI.service';
export * from './storageLockerAPI.service';
import { StorageLockerAPIService } from './storageLockerAPI.service';
export * from './storageShelfAPI.service';
import { StorageShelfAPIService } from './storageShelfAPI.service';
export * from './transportationAPI.service';
import { TransportationAPIService } from './transportationAPI.service';
export * from './transportationTripAPI.service';
import { TransportationTripAPIService } from './transportationTripAPI.service';
export * from './workPositionAPI.service';
import { WorkPositionAPIService } from './workPositionAPI.service';
export const APIS = [AuthAPIService, BranchAPIService, BranchScheduleAPIService, EmployeeAPIService, MailPackageAPIService, MailPackageAssignationAPIService, MailPackageStatusAPIService, PermissionAPIService, ServicePriceAPIService, StorageLockerAPIService, StorageShelfAPIService, TransportationAPIService, TransportationTripAPIService, WorkPositionAPIService];
