/**
 * PaqueteriaCB API
 * REST Api documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BranchScheduleDto } from './branchScheduleDto';


export interface BranchDto { 
    colony?: string;
    county?: string;
    createdAt?: string;
    id?: number;
    lat?: number;
    lng?: number;
    name?: string;
    number?: string;
    schedules?: Set<BranchScheduleDto>;
    street?: string;
    updatedAt?: string;
}

