/**
 * PaqueteriaCB API
 * REST Api documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageStorageShelfDto } from './pageStorageShelfDto';


export interface GenericResponsePageStorageShelfDto { 
    data?: PageStorageShelfDto;
    message?: string;
    success?: boolean;
}

