/**
 * PaqueteriaCB API
 * REST Api documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MailPackageDto { 
    deliverBranchId?: number;
    deliverBranchName?: string;
    delivered?: string;
    deliveryPrice?: number;
    deliveryPriceId?: number;
    from?: string;
    id?: number;
    initialBranchId?: number;
    initialBranchName?: string;
    packageStatus?: string;
    packageStatusId?: number;
    received?: string;
    storagePrice?: number;
    storagePriceId?: number;
    to?: string;
    totalPrice?: number;
    transfer?: boolean;
    transportationCompleted?: boolean;
    transportationId?: number;
    weeks?: number;
}

