/**
 * PaqueteriaCB API
 * REST Api documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Pagination { 
    pageNum?: number;
    pageSize?: number;
    sortBy?: string;
    sortDirection?: Pagination.SortDirectionEnum;
}
export namespace Pagination {
    export type SortDirectionEnum = 'ASC' | 'DESC';
    export const SortDirectionEnum = {
        Asc: 'ASC' as SortDirectionEnum,
        Desc: 'DESC' as SortDirectionEnum
    };
}


