/**
 * PaqueteriaCB API
 * REST Api documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SearchCondition { 
    operation?: SearchCondition.OperationEnum;
    property?: string;
    value?: object;
}
export namespace SearchCondition {
    export type OperationEnum = 'BETWEEN' | 'CONTAINS' | 'EQUAL' | 'GREATER_THAN' | 'IS_NOT_NULL' | 'IS_NULL' | 'LESS_THAN' | 'NOT_CONTAINS' | 'NOT_EQUAL';
    export const OperationEnum = {
        Between: 'BETWEEN' as OperationEnum,
        Contains: 'CONTAINS' as OperationEnum,
        Equal: 'EQUAL' as OperationEnum,
        GreaterThan: 'GREATER_THAN' as OperationEnum,
        IsNotNull: 'IS_NOT_NULL' as OperationEnum,
        IsNull: 'IS_NULL' as OperationEnum,
        LessThan: 'LESS_THAN' as OperationEnum,
        NotContains: 'NOT_CONTAINS' as OperationEnum,
        NotEqual: 'NOT_EQUAL' as OperationEnum
    };
}


