/**
 * PaqueteriaCB API
 * REST Api documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransportationDto { 
    completed?: boolean;
    destinyBranchId?: number;
    destinyBranchName?: string;
    id?: number;
    originBranchId?: number;
    originBranchName?: string;
    transportationTripId?: number;
}

